### ISSUE TITLE
.deb packages for debian wheezy?

### ISSUE THREAD

**Issue by ghost** [npd6/npd6#66]
Hi,

seems the current packages provided at:

https://github.com/npd6/npd6/releases

are not installable on debian wheezy because the dependency to a newer libc6 package:

> Unpacking npd6 (from npd6_1.1.0_amd64.deb) ...
> dpkg: dependency problems prevent configuration of npd6:
> npd6 depends on libc6 (>= 2.15); however:
>  Version of libc6:amd64 on system is 2.13-38+deb7u3

As wheezy is widely used are there any chances to get .deb packages for it?

Thanks in advance.

**Comment by npd6** [comment]
Hi. Many thanks for identifying this.

Moving to github from GoogleCode has been bumpy (!) but I think we're there... So let me look at this item in the next day or two and get it sorted.

Thanks!

Sean

**Comment by alteholz** [comment]
What do you think of official Debian packages?

**Comment by npd6** [comment]
Closing from so long ago - tidying up old issues. npd6 has been in main Ubuntu/Debian etc for a while, so the need for me to build packages no longer required. Thankfully.
