### ISSUE TITLE
man pages 

### ISSUE THREAD

**Issue by alteholz** [npd6/npd6#69]
It is a bit strange that you commited your man pages as compressed file, though here is a diff after checking with lintian:

--- ../npd6.conf.5      2017-02-14 19:27:20.077801273 +0100
+++ npd6.conf.5 2017-02-14 20:01:11.431844923 +0100
@@ -7,7 +7,7 @@
 .SH DESCRIPTION
 This file contains parameters which affect the manner of npd6's operation. The first section contain a few common parameters - you will need to change these to suit your situation. The second set are less likely to require changing and will typically work fine at their default value. In fact: if you change the second set and get it wrong, npd6 may work badly, intermittently or not at all. Leave them alone unless you have a real reason to change them!
 
-All these paremeters can be dauting. Fear not! Probably 95% of the folks who use npd6 have received a 64-bit prefix from their ISP and want to have their box answer neighbor solicitations for the prefix on, maybe, interface eth0. And that's all they want. So read a bit of General Parameters below and set your one prefix and one interface and happily leave everything else alone... It'll work great for you. 
+All these parameters can be dauting. Fear not! Probably 95% of the folks who use npd6 have received a 64-bit prefix from their ISP and want to have their box answer neighbor solicitations for the prefix on, maybe, interface eth0. And that's all they want. So read a bit of General Parameters below and set your one prefix and one interface and happily leave everything else alone... It'll work great for you. 
 
 
 .SS General parameters
@@ -142,11 +142,11 @@
 Default: off
 .RE
 
-.B List-type precendence
+.B List-type precedence
 
 Note that 
 .B exprlist
-values take precendence over
+values take precedence over
 .B addrlist
 values (if both are specified)
 
@@ -170,7 +170,7 @@
 .RS
 Optionally, npd6 can record a list of targets received in the incoming Neighbor Solicitations, to which it has replied. These can be displayed in the defined log by sending a USR2 signal npd6. e.g. kill -USR2 <pid of npd6>
 
-This paramater defines a limit to the number of addresses recorded. If the value is zero, then the feature is disabled. This is the default behaviour. The paramater should be set to a suitably large but sane value. The only significant overhead is memory (for storing the addresses) Given the address space of IPv6 and the possibility of receving very many different target addresses to not provide a ceiling to this feature would potentially open npd6 up to a denial-of-service based upon memory depletion.
+This parameter defines a limit to the number of addresses recorded. If the value is zero, then the feature is disabled. This is the default behaviour. The parameter should be set to a suitably large but sane value. The only significant overhead is memory (for storing the addresses) Given the address space of IPv6 and the possibility of receiving very many different target addresses to not provide a ceiling to this feature would potentially open npd6 up to a denial-of-service based upon memory depletion.
 
 In a typical situation, where a network might expect to receive Neighbor Solicitations for several dozen devices, there's likely no harm in setting this to 100 or 1000. Just don't set it at 10,000,000 without thinking first. Memory is only allocated as-required - if you do set a high limit, npd6 does not preallocate the memory, but only use it as and if required.

**Comment by npd6** [comment]
Yup. Typos to be fixed. Imminent.

**Comment by npd6** [comment]
Fixed in tag 1.1.1/dev2
